from __future__ import annotations

import argparse
import json
from pathlib import Path

from .commands import ensure_parent, require_executable, run_command
from .step import export_mesh_wrapper_step


def _cube_mesh() -> tuple[list[tuple[float, float, float]], list[tuple[int, int, int]]]:
    size = 25.0
    half = size / 2.0
    vertices = [
        (-half, -half, -half),
        (half, -half, -half),
        (half, half, -half),
        (-half, half, -half),
        (-half, -half, half),
        (half, -half, half),
        (half, half, half),
        (-half, half, half),
    ]
    faces = [
        (1, 2, 3),
        (1, 3, 4),
        (5, 8, 7),
        (5, 7, 6),
        (1, 5, 6),
        (1, 6, 2),
        (2, 6, 7),
        (2, 7, 3),
        (3, 7, 8),
        (3, 8, 4),
        (4, 8, 5),
        (4, 5, 1),
    ]
    return vertices, faces


def _write_obj(path: Path, vertices: list[tuple[float, float, float]], faces: list[tuple[int, int, int]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# generated by coffee-nerf-cad"]
    lines.extend(f"v {x} {y} {z}" for x, y, z in vertices)
    lines.extend(f"f {a} {b} {c}" for a, b, c in faces)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_ascii_stl(
    path: Path, vertices: list[tuple[float, float, float]], faces: list[tuple[int, int, int]]
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["solid example_cube"]
    for face in faces:
        lines.append("  facet normal 0 0 0")
        lines.append("    outer loop")
        for index in face:
            x, y, z = vertices[index - 1]
            lines.append(f"      vertex {x} {y} {z}")
        lines.append("    endloop")
        lines.append("  endfacet")
    lines.append("endsolid example_cube")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_minimal_3mf(
    path: Path, vertices: list[tuple[float, float, float]], faces: list[tuple[int, int, int]]
) -> None:
    import zipfile

    path.parent.mkdir(parents=True, exist_ok=True)
    model_vertices = "\n".join(f'<vertex x="{x}" y="{y}" z="{z}" />' for x, y, z in vertices)
    model_faces = "\n".join(
        f'<triangle v1="{a - 1}" v2="{b - 1}" v3="{c - 1}" />' for a, b, c in faces
    )
    model = f'''<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
  <resources>
    <object id="1" type="model">
      <mesh>
        <vertices>
{model_vertices}
        </vertices>
        <triangles>
{model_faces}
        </triangles>
      </mesh>
    </object>
  </resources>
  <build>
    <item objectid="1" />
  </build>
</model>
'''
    relationships = '''<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel" />
</Relationships>
'''
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("3D/3dmodel.model", model)
        archive.writestr("_rels/.rels", relationships)


class _WrapperMesh:
    def __init__(self, vertex_count: int, face_count: int) -> None:
        self.vertices = range(vertex_count)
        self.faces = range(face_count)


def cmd_colmap(args: argparse.Namespace) -> None:
    require_executable("ns-process-data")
    command = [
        "ns-process-data",
        "images",
        "--data",
        str(args.images),
        "--output-dir",
        str(args.output),
        "--matching-method",
        "exhaustive",
    ]
    run_command(command, dry_run=args.dry_run)


def cmd_train(args: argparse.Namespace) -> None:
    require_executable("ns-train")
    command = ["ns-train", "nerfacto", "--data", str(args.data), "--output-dir", str(args.output)]
    run_command(command, dry_run=args.dry_run)


def cmd_extract(args: argparse.Namespace) -> None:
    require_executable("ns-export")
    ensure_parent(args.output)
    command = [
        "ns-export",
        args.method,
        "--load-config",
        str(args.config),
        "--output-dir",
        str(args.output.parent),
    ]
    run_command(command, dry_run=args.dry_run)


def cmd_clean(args: argparse.Namespace) -> None:
    from .mesh import clean_mesh, export_mesh, load_mesh, mesh_report

    mesh = clean_mesh(load_mesh(args.input))
    export_mesh(mesh, args.output)
    print(json.dumps(mesh_report(mesh), indent=2))


def cmd_export(args: argparse.Namespace) -> None:
    from .mesh import clean_mesh, export_mesh, load_mesh, mesh_report

    mesh = clean_mesh(load_mesh(args.input))
    mesh.metadata["units"] = args.unit
    export_mesh(mesh, Path("outputs/stl") / f"{args.name}.stl")
    export_mesh(mesh, Path("outputs/3mf") / f"{args.name}.3mf")
    export_mesh_wrapper_step(mesh, Path("outputs/step") / f"{args.name}.step", args.name)
    print(json.dumps(mesh_report(mesh), indent=2))


def cmd_inspect(args: argparse.Namespace) -> None:
    from .mesh import load_mesh, mesh_report

    mesh = load_mesh(args.input)
    print(json.dumps(mesh_report(mesh), indent=2))


def cmd_example(_: argparse.Namespace) -> None:
    vertices, faces = _cube_mesh()
    _write_obj(Path("outputs/meshes/example_cube.obj"), vertices, faces)
    _write_ascii_stl(Path("outputs/stl/example_cube.stl"), vertices, faces)
    _write_minimal_3mf(Path("outputs/3mf/example_cube.3mf"), vertices, faces)
    export_mesh_wrapper_step(_WrapperMesh(len(vertices), len(faces)), Path("outputs/step/example_cube.step"), "example_cube")
    print(json.dumps({"vertices": len(vertices), "faces": len(faces), "watertight": True}, indent=2))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="coffee-nerf-cad")
    subparsers = parser.add_subparsers(dest="command", required=True)

    colmap_parser = subparsers.add_parser("colmap")
    colmap_parser.add_argument("--images", type=Path, default=Path("input/images"))
    colmap_parser.add_argument("--output", type=Path, default=Path("outputs/colmap"))
    colmap_parser.add_argument("--dry-run", action="store_true")
    colmap_parser.set_defaults(func=cmd_colmap)

    train_parser = subparsers.add_parser("train")
    train_parser.add_argument("--data", type=Path, required=True)
    train_parser.add_argument("--output", type=Path, default=Path("outputs/nerfstudio"))
    train_parser.add_argument("--dry-run", action="store_true")
    train_parser.set_defaults(func=cmd_train)

    extract_parser = subparsers.add_parser("extract")
    extract_parser.add_argument("--config", type=Path, required=True)
    extract_parser.add_argument("--output", type=Path, required=True)
    extract_parser.add_argument("--method", default="marching-cubes")
    extract_parser.add_argument("--dry-run", action="store_true")
    extract_parser.set_defaults(func=cmd_extract)

    clean_parser = subparsers.add_parser("clean")
    clean_parser.add_argument("--input", type=Path, required=True)
    clean_parser.add_argument("--output", type=Path, required=True)
    clean_parser.set_defaults(func=cmd_clean)

    export_parser = subparsers.add_parser("export")
    export_parser.add_argument("--input", type=Path, required=True)
    export_parser.add_argument("--name", default="reconstruction")
    export_parser.add_argument("--unit", default="mm")
    export_parser.set_defaults(func=cmd_export)

    inspect_parser = subparsers.add_parser("inspect")
    inspect_parser.add_argument("--input", type=Path, required=True)
    inspect_parser.set_defaults(func=cmd_inspect)

    example_parser = subparsers.add_parser("example")
    example_parser.set_defaults(func=cmd_example)
    return parser


def main() -> None:
    args = build_parser().parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
